version: '2.0'
services:
  postgres:
    image: postgres
    restart: always
    container_name: hackathon
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: hackathon
      POSTGRES_USER: hackathon
      POSTGRES_PASSWORD: hackathon
    volumes:
      - ./data:/var/lib/postgresql/data
volumes:
  postgres: